// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveSystemTalonFrontLeft;
std::shared_ptr<CANTalon> RobotMap::driveSystemTalonFrontRight;
std::shared_ptr<CANTalon> RobotMap::driveSystemTalonBackLeft;
std::shared_ptr<CANTalon> RobotMap::driveSystemTalonBackRight;
std::shared_ptr<RobotDrive> RobotMap::driveSystemRobotDrive41;
std::shared_ptr<Solenoid> RobotMap::gearShiftGearShifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveSystemTalonFrontLeft.reset(new CANTalon(0));
    lw->AddActuator("DriveSystem", " TalonFrontLeft", driveSystemTalonFrontLeft);
    
    driveSystemTalonFrontRight.reset(new CANTalon(1));
    lw->AddActuator("DriveSystem", "TalonFrontRight", driveSystemTalonFrontRight);
    
    driveSystemTalonBackLeft.reset(new CANTalon(3));
    lw->AddActuator("DriveSystem", "TalonBackLeft", driveSystemTalonBackLeft);
    
    driveSystemTalonBackRight.reset(new CANTalon(2));
    lw->AddActuator("DriveSystem", "TalonBackRight", driveSystemTalonBackRight);
    
    driveSystemRobotDrive41.reset(new RobotDrive(driveSystemTalonFrontLeft, driveSystemTalonBackLeft,
              driveSystemTalonFrontRight, driveSystemTalonBackRight));
    
    driveSystemRobotDrive41->SetSafetyEnabled(false);
        driveSystemRobotDrive41->SetExpiration(0.1);
        driveSystemRobotDrive41->SetSensitivity(0.5);
        driveSystemRobotDrive41->SetMaxOutput(1.0);

    gearShiftGearShifter.reset(new Solenoid(0, 0));
    lw->AddActuator("GearShift", "GearShifter", gearShiftGearShifter);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
